name: Compilador Cloud VIVO
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Get Buildozer Update
        run: |
          pip3 install --user --upgrade buildozer
          pip3 install --user --upgrade Cython virtualenv

      - name: Build with Buildozer
        run: |
          buildozer android debug
